version: "3.9"
services:
  api:
    build: .
    container_name: shortener-api
    restart: unless-stopped
    env_file: .env
    environment:
      - PYTHONPATH=/app/src
      - APP_ENV="dev"
    ports:
      - "5001:5001"
